version: '3.8'

services:

  directus:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./snapshots:/directus/snapshots
    environment:
      EXTENSIONS_AUTO_RELOAD: 'true'
      REFRESH_TOKEN_COOKIE_SAME_SITE: 'None'
      PUBLIC_URL: 'http://localhost:3000'
      # ACCESS_TOKEN_TTL: '2m'

      PASSWORD_RESET_URL_ALLOW_LIST: 'http://localhost:3000/reset-password'

  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
      target: base
    environment:
      NODE_ENV: 'development'
      NUXT_DIRECTUS_URL: 'http://host.docker.internal:8055'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "24678:24678"
    volumes:
      - ./frontend/src:/opt/node_app/app/src
      - ./frontend/.npmrc:/opt/node_app/app/.npmrc
      - ./frontend/nuxt.config.ts:/opt/node_app/app/nuxt.config.ts
      - ./frontend/tailwind.config.ts:/opt/node_app/app/tailwind.config.ts
      - ./frontend/tsconfig.json:/opt/node_app/app/tsconfig.json
      - ./frontend/package.json:/opt/node_app/app/package.json
      - ./frontend/package-lock.json:/opt/node_app/app/package-lock.json
    command: ["/wait-for", "http://directus:8055/server/ping", "-t", "30", "--", "npm", "run", "dev"]
