version: '3.8'

services:

  directus:
    container_name: mcc-backend-playground
    restart: unless-stopped
    ports:
      - "8055:8055"
    networks:
      - directus
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
      - ./extensions:/directus/extensions
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'true'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: "*"

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'

      EMAIL_FROM: 'no-reply@mattclegg.dev'
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

      PASSWORD_RESET_URL_ALLOW_LIST: 'https://mccdev.co.uk/reset-password'

  frontend:
    depends_on:
      - directus
    container_name: mcc-frontend-playground
    environment:
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    networks:
      - directus
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: ["/wait-for", "http://directus:8055/server/ping", "-t", "10", "--", "node", ".output/server/index.mjs"]

networks:
  directus:
