version: '3.8'

services:
  
  directus:
    image: ghcr.io/maidstone-canoe-club/playground-backend:latest
    environment:
      PUBLIC_URL: 'https://mccdev.co.uk/cms'
  
  frontend:
    image: ghcr.io/maidstone-canoe-club/playground-frontend:latest
    environment:
      - DIRECTUS_URL=https://mccdev.co.uk/cms